version: '3.7'
services: 
  database:
    container_name: reddit-clone
    image: mysql
    volumes:
      - "./data:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
